export const properties = [
  {
    id: 1,
    title: "Люкс Вилла с видом на море",
    location: "Судак, Центр",
    price: 8500,
    rating: 4.9,
    reviews: 128,
    guests: 6,
    image: "/luxury-villa-sudak-sea-view.jpg",
    type: "Вилла",
    amenities: ["Wi-Fi", "Кухня", "Бассейн", "Терраса"],
    description:
      "Роскошная вилла с панорамным видом на Черное море. Идеально подходит для семей и компаний друзей. Частный доступ к пляжу, современные удобства и атмосфера люкса.",
    fullAmenities: ["Wi-Fi", "Кухня", "Бассейн", "Терраса", "Кондиционер", "Парковка", "Сейф", "Полотенца", "Фен"],
    images: [
      "/luxury-villa-sudak-sea-view.jpg",
      "/luxury-villa-terrace-with-sea-view.jpg",
      "/luxury-villa-bedroom.png",
      "/luxury-villa-pool.png",
    ],
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    id: 2,
    title: "Уютные апартаменты у пляжа",
    location: "Судак, Пляжная зона",
    price: 4200,
    rating: 4.8,
    reviews: 94,
    guests: 4,
    image: "/cozy-beachfront-apartment-sudak.jpg",
    type: "Апартаменты",
    amenities: ["Wi-Fi", "Кондиционер", "Терраса", "Паркинг"],
    description:
      "Уютные апартаменты в 50 метрах от пляжа. Прекрасный вид на море, современный интерьер, все необходимое для комфортного отдыха.",
    fullAmenities: [
      "Wi-Fi",
      "Кондиционер",
      "Терраса",
      "Паркинг",
      "Кухня",
      "Холодильник",
      "Микроволновая печь",
      "Телевизор",
    ],
    images: [
      "/cozy-beachfront-apartment-sudak.jpg",
      "/beachfront-apartment-terrace.jpg",
      "/beachfront-apartment-bedroom.jpg",
      "/beachfront-apartment-kitchen.jpg",
    ],
    bedrooms: 2,
    bathrooms: 1,
  },
  {
    id: 3,
    title: "Двухэтажный дом на берегу",
    location: "Судак, Новый Свет",
    price: 6800,
    rating: 4.7,
    reviews: 76,
    guests: 8,
    image: "/two-story-beachfront-house-sudak.jpg",
    type: "Дом",
    amenities: ["Wi-Fi", "Кухня", "Сад", "Вид на море"],
    description:
      "Просторный двухэтажный дом с видом на море. Идеален для больших компаний и семейных праздников. Собственный участок, барбекю и открытая терраса.",
    fullAmenities: ["Wi-Fi", "Кухня", "Сад", "Вид на море", "Барбекю", "Парковка", "Балкон", "Стиральная машина"],
    images: [
      "/two-story-beachfront-house-sudak.jpg",
      "/two-story-house-sea-view.jpg",
      "/two-story-house-garden.jpg",
      "/two-story-house-terrace.jpg",
    ],
    bedrooms: 4,
    bathrooms: 2,
  },
  {
    id: 4,
    title: "Панорамные апартаменты",
    location: "Судак, Нагорная",
    price: 5900,
    rating: 4.9,
    reviews: 112,
    guests: 4,
    image: "/panoramic-apartments-sudak-mountains.jpg",
    type: "Апартаменты",
    amenities: ["Wi-Fi", "Балкон", "Кондиционер", "Парковка"],
    description:
      "Апартаменты с панорамным видом на море и горы. Отличное месторасположение на возвышенности, идеально для восхода и заката.",
    fullAmenities: [
      "Wi-Fi",
      "Балкон",
      "Кондиционер",
      "Парковка",
      "Кухня",
      "Холодильник",
      "Телевизор",
      "Климат-контроль",
    ],
    images: [
      "/panoramic-apartments-sudak-mountains.jpg",
      "/panoramic-apartment-balcony-sunset.jpg",
      "/panoramic-apartment-interior.jpg",
      "/panoramic-apartment-mountain-view.jpg",
    ],
    bedrooms: 2,
    bathrooms: 1,
  },
  {
    id: 5,
    title: "Морская коттедж семейный",
    location: "Судак, Весёлое",
    price: 5500,
    rating: 4.8,
    reviews: 85,
    guests: 6,
    image: "/family-seaside-cottage-sudak.jpg",
    type: "Коттедж",
    amenities: ["Кухня", "Барбекю", "Игровая площадка", "Сад"],
    description:
      "Уютный семейный коттедж с барбекю и игровой площадкой. Идеален для отдыха с детьми. Близко к морю и центру.",
    fullAmenities: [
      "Кухня",
      "Барбекю",
      "Игровая площадка",
      "Сад",
      "Парковка",
      "Стиральная машина",
      "Холодильник",
      "Полотенца",
    ],
    images: [
      "/family-seaside-cottage-sudak.jpg",
      "/family-cottage-backyard.jpg",
      "/family-cottage-garden.jpg",
      "/family-cottage-terrace.jpg",
    ],
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    id: 6,
    title: "Студия с прямым выходом на пляж",
    location: "Судак, Центр",
    price: 3200,
    rating: 4.6,
    reviews: 64,
    guests: 2,
    image: "/beach-studio-sudak-direct-access.jpg",
    type: "Студия",
    amenities: ["Wi-Fi", "Кондиционер", "Балкон", "Холодильник"],
    description:
      "Небольшая, но уютная студия с прямым выходом на пляж. Идеально для пар и одиночных путешественников. Минимализм и комфорт в одном месте.",
    fullAmenities: ["Wi-Fi", "Кондиционер", "Балкон", "Холодильник", "Кухня", "Телевизор", "Полотенца", "Фен"],
    images: [
      "/beach-studio-sudak-direct-access.jpg",
      "/beach-studio-balcony.jpg",
      "/beach-studio-interior.jpg",
      "/placeholder.svg?height=400&width=600",
    ],
    bedrooms: 1,
    bathrooms: 1,
  },
]
